---
- name: "Check Graylog configuration."
  include_tasks: check-configuration.yml

- name: "Install Graylog prerequisites."
  apt:
    name: "{{ graylog_prerequisites }}"
    state: present

- name: "Create a temporary file ton save Graylog .deb."
  tempfile:
    state: file
    prefix: graylog_
    suffix: .deb
  register: graylog_tmp_file
  changed_when: false
  when: not ansible_check_mode

- name: "Get Graylog .deb (repos url + keyring installation)."
  get_url:
    url: "{{ graylog_repos_deb_url }}"
    dest: "{{ graylog_tmp_file.path }}"
    force: true
  changed_when: false
  when: not ansible_check_mode

- name: "Install Graylog repository + keyring."
  apt:
    deb: "{{ graylog_tmp_file.path }}"
    state: present
    dpkg_options: force-all
  when: not ansible_check_mode

- name: "Remove temporary Graylog .deb file."
  file:
    path: "{{ graylog_tmp_file.path }}"
    state: absent
  changed_when: false
  when: not ansible_check_mode

- name: "Include tasks to install Graylog."
  include_tasks: install_pkgs.yml
  vars:
    _pkg_to_install: "{{ graylog_pkg_name }}"

- name: "Include tasks to install Graylog integrations plugins if needed."
  include_tasks: install_pkgs.yml
  vars:
    _pkg_to_install: "{{ graylog_intagration_pkg_name }}"
  when: graylog_install_integration

- name: "Include tasks to install Graylog enterprise plugins if needed."
  include_tasks: install_pkgs.yml
  loop: "{{ graylog_enterprise_pkg_name }}"
  loop_control:
    loop_var: _pkg_to_install
  when: graylog_install_enterprise

- name: "Configure Graylog service."
  service:
    name: "{{ graylog_svc_name }}"
    enabled: "{{ graylog_svc_enabled }}"
    state: "{{ graylog_svc_state }}"

- name: "Configure Graylog java default values."
  template:
    src: default_graylog.j2
    dest: /etc/default/graylog-server
    mode: 0644
  notify: "Restart Graylog."

- name: "Configure Graylog."
  template:
    src: graylog-server.conf.j2
    dest: /etc/graylog/server/server.conf
    owner: graylog
    group: graylog
    mode: 0640
  notify: "Restart Graylog."

- name: "Install Graylog plugins."
  include_tasks: plugins.yml
